---
title: "Untitled"
author: "Man Adrian Ho Hin"
date: '2023-04-14'
output: word_document
---

```{r}
rm(list=ls())
```

# Question 4
```{r}
n = 100
beta1 = 1
beta2 = 0.5
beta3 = 2
library(MASS)
sigma = cbind(c(1,0.8), c(0.8,1))
eu = mvrnorm(n, c(0,0), sigma)
e = eu[,1]
u = eu[,2]

z1 = rnorm(n,1,1)
z2 = rgamma(n,2)
z3 = rnorm(n,1,2)
x2 = z1+0.5*z2+0.01*z3+u
x1 = rnorm(n,1,2)

y = beta1 + beta2*x1 + beta3*x2 + e
```

```{r}
nseq = seq(100, 5000, by=100)
ols = NULL
se = NULL
set.seed(1)
for (n in nseq){
  beta1 = 1
  beta2 = 0.5
  beta3 = 2
  library(MASS)
  sigma = cbind(c(1,0.8), c(0.8,1))
  eu = mvrnorm(n, c(0,0), sigma)
  e = eu[,1]
  u = eu[,2]
  
  z1 = rnorm(n,1,1)
  z2 = rgamma(n,2)
  z3 = rnorm(n,1,2)
  x2 = z1+0.5*z2+0.01*z3+u
  x1 = rnorm(n,1,2)
  
  y = beta1 + beta2*x1 + beta3*x2 + e
  
  m1 = summary(lm(y~x1+x2))
  ols = rbind(ols, m1$coef[,1])
  se = rbind(se, m1$coef[,2])
}

plot(nseq, ols[,1], type="l", ylim=c(0.1,1.5))
abline(h=beta1,col=2,lty=2)

plot(nseq, ols[,2], type="l", ylim=c(0,1))
abline(h=beta2,col=2,lty=2)

plot(nseq, ols[,3], type="l", ylim=c(1.5,3))
abline(h=beta3,col=2,lty=2)
```

```{r}
set.seed(1)
n = 100
beta1 = 1
beta2 = 0.5
beta3 = 2
library(MASS)
sigma = cbind(c(1,0.8), c(0.8,1))
eu = mvrnorm(n, c(0,0), sigma)
e = eu[,1]
u = eu[,2]

z1 = rnorm(n,1,1)
z2 = rgamma(n,2)
z3 = rnorm(n,1,2)
x2 = z1+0.5*z2+0.01*z3+u # for the next part, the iv should have strong correlation with x2 (x2 & z3), also a very high standard as improper iv
x1 = rnorm(n,1,2)

y = beta1 + beta2*x1 + beta3*x2 + e

ols = lm(y~x1+x2)
iv1 = ivreg(y~x1+x2|x1+z1)
iv2 = ivreg(y~x1+x2|x1+z2)
iv3 = ivreg(y~x1+x2|x1+z3)
iv4 = ivreg(y~x1+x2|x1+z1+z2+z3)

stargazer(ols,iv1,iv2,iv3,iv4,type="text")

```






